# Generated by Django 3.1.1 on 2021-09-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchneighborhood', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='images'),
        ),
    ]
