# Generated by Django 3.2.7 on 2021-09-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchneighborhood', '0003_auto_20210924_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_pic',
            field=models.ImageField(default='nopicture.png', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='business',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='neighborhood',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
